name: mc_navigator
description: "A new Flutter package project."
version: 0.0.4
homepage: https://multicaret.com

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  open_share_plus: ^1.3.0
  navigation_history_observer: ^1.1.1
  built_collection: ^5.1.1
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
